### ISSUE TITLE
Постоянно синхронизируется файл mytetra.xml

### ISSUE THREAD

**Issue by sdfq** [gee12/MyTetroid#10]
Если делать изменения только с компьютера и синхронизироваться, то нормально в коммите только эти изменения.
Если синхронизироваться с телефоном, и потом сделать изменения на телефоне то синхронизируется полностью весь файл xml

Добавил только одну ноду а mytetra.xml полностью переписался:
Showing with 430 additions and 429 deletions 

Если добавлять ноды только на компьютере добавляется только по одной строчка в mytetra.xml

**Comment by gee12** [comment]
Привет. Спасибо за отзыв. Выйду из отпуска - буду смотреть. Может быть
проблема в разных форматах сохранения отступов в документе (windows/unix)

пн, 13 июля 2020, 7:54 sdfq <notifications@github.com>:

**Comment by sdfq** [comment]
Хм интересно, на компе xubunutu

**Comment by gee12** [comment]
Проблема была в лишнем пробеле перед закрытием тега " />".
Исправлено в версии 4.0.
