### ISSUE TITLE
Метки в списке заметок, как в настольной MyTetra

### ISSUE THREAD

**Issue by IMMSPgisgroup** [gee12/MyTetroid#11]
Нельзя ли добавить в списке заметок, как опцию, отображение меток этих заметок? Как это сделано в MyTetra. По этим меткам можно понять содержимое заметки, что во многих случаях помогает выбрать нужную заметку без использования поиска.
Вообще, приложение хорошее и полезное. Скопировал свою персональную базу знаний MyTetra на смартфон :).

**Comment by gee12** [comment]
Можно. Давно планировалось сделать регулируемый список выводимых свойств заметок. Пожалуй, могу начать с простого, просто добавить галку на отображение меток.
Спасибо за отзыв, пишите об ошибках.

**Comment by gee12** [comment]
Добавлено в версии 4.1.
