### ISSUE TITLE
Не работает переход по ссылке на заметку. 

### ISSUE THREAD

**Issue by IMMSPgisgroup** [gee12/MyTetroid#16]
Не работает переход по ссылке из одной заметки в другую, для которой указан адрес формата MyTetra (mytetra://note/*******). В MyTetra работает, а в MyTetroid Pro 5.4.1 нет. Прилагаю, на всякий случай, маленькую базу с примером.
[data02.zip](https://github.com/gee12/MyTetroid/files/14038161/data02.zip)

**Comment by gee12** [comment]
Спасибо. Исправил, будет в версии 5.7.

**Comment by gee12** [comment]
Коммит: 7803a5cdfe1eb03edc279451e7415dccca2ac276
