### ISSUE TITLE
Bug: tags not shown in the right drawer

### ISSUE THREAD

**Issue by dcdom2** [gee12/MyTetroid#21]
You must tap "tag search" then back (the x button) for tags to show. I think this happens if all nodes are encrypted and the app asks for password.

**Comment by gee12** [comment]
@dcdom2  I think I've reproduced the bug, thanks. 
But there is a discrepancy in the issue title: there should be no tags in the left drawer, there is a list of nodes. Probably meant the right drawer?

**Comment by gee12** [comment]
Fixed [here](https://github.com/gee12/MyTetroid/commit/707e1dbb3e4d3eadbda1a7102c8e7e71f668fded), will be published in version 5.10.

**Comment by dcdom2** [comment]
>Probably meant the right drawer?

Yes you are right. my mistake.
