### ISSUE TITLE
Открытие зашифрованных веток - доделать, чтобы не было сегфолта

### ISSUE THREAD

**Issue by xintrea** [gee12/MyTetroid#3]
При ввтоде неправильного пароля - программа видит что пароль неправильный, и показывает сообщение.

При вводе правильного пароля программа молча закрывается.

**Comment by gee12** [comment]
Не получается воссоздать ошибку. На двух разных хранилищах с зашифрованными ветками и на Android 4.4 и 6.0. Отправить мне ваше хранилище я просить не могу. У вас рутованное устройство? Логи отправить сможете?

**Comment by gee12** [comment]
Возможен OutOfMemoryError при расшифровке больших записей (например, html файл около 20Мб). Нужно оптимизировать алгоритм расшифровки.
